#encoding:UTF-8
headTextDict={}
headTextLabList=[]
headTextTabList=[]
#UI_DEFINE_STRING_HEADTEXT_TYPETEXT

UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T1=u"T1"
UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T2=u"T2"
UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T3=u"T3"
UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T4=u"T4"
UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T5=u"T5"
UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T6=u"T6"
UI_DEFINE_STRING_HEADTEXT_TYPETEXT_T7=u"T7"

#T1
UI_DEFINE_STRING_HEADTEXT_T1_TABNAME_S1=u""
UI_DEFINE_STRING_HEADTEXT_T1_TABNAME_S2=u""
UI_DEFINE_STRING_HEADTEXT_T1_TABNAME_S3=u""
UI_DEFINE_STRING_HEADTEXT_T1_TABNAME_S4=u""
UI_DEFINE_STRING_HEADTEXT_T1_TABNAME_S5=u""


UI_DEFINE_STRING_HEADTEXT_TABDICT_NAME=u"TabName"
UI_DEFINE_STRING_HEADTEXT_TABDICT_VALUE=u"BarTitleNames"
UI_DEFINE_STRING_HEADTEXT_NOTAB = u"NoTab"
UI_DEFINE_STRING_QTDCONFIGDIR=u'QTDConfig/'
UI_DEFINE_STRING_INDEXFILE = UI_DEFINE_STRING_QTDCONFIGDIR+u'indexView.json'



UI_DEFINE_LIST_QUERYSTOCKINFORMATION_HEADTEXT=[u'股票代码',u'股票名称',u'最新',u'涨幅',u'涨跌',u'涨速',u'大单净量',u'总手',u'换手',u'量比',u'现手',u'开盘',u'作收',u'最高',u'最低',u'市盈（动',u'市净率',u'委比',u'振幅',u'总市值']
UI_DEFINE_LIST_KLINE_BS_HEADTEXT=[u'五档',u'明细']
UI_DEFINE_LIST_KLINE_BS_ROWTEXT=[u'卖5',u'卖4',u'卖3',u'卖2',u'卖1',u'买1',u'买2',u'买3',u'买4',u'买5']
UI_DEFINE_LIST_STOCKCUSTOMER=[u'股票代码',u'策略',u'风控',u'监控',u'选股',u'组合',u'仓位',u'资金']
UI_DEFINE_LIST_STOCKSELECTION=[u'股票代码']
UI_DEFINE_LIST_LOGSELECTEDLIST=[u'全部显示',u'系统提示',u'操作提示',u'交易提示',u'错误提示']
UI_DEFINE_LIST_INDEXVIEW=[u'view1']

UI_DEFINE_DICT_1_STOCKPOOL={u'股票池':[u'股票代码',u'股票名称']}
UI_DEFINE_DICT_1_MANULTRIGGERSELLTRADE={u'手动出发单(卖)':[]}
UI_DEFINE_DICT_1_MANULTRIGGERBUYTRADE={u'手动出发单(买)':[]}
UI_DEFINE_DICT_1_HOLDSTORAGE={u'持仓':[u'股票代码',u'买卖',u'成本价',u'持仓数量',u'可用数量',u'挂盘数量',u'浮动盈亏']}
UI_DEFINE_DICT_1_TRANSACTIONLIST={u'成交一览':[u'成交时间',u'成交价',u'成交量',u'成交额']}
UI_DEFINE_DICT_1_TOTALCOMMISSION={u'全部委托':[u'委托时间',u'委托/均价',u'委托/成交',u'状态']}
UI_DEFINE_DICT_1_LOG={u'日志':[u'时间',u'日志类型',u'系统信息']}
UI_DEFINE_DICT_1_CAPITAL={u'资金状况':[u'总资产',u'浮动盈亏',u'总市值',u'可取',u'可用']}
